sonar.organization=azconcept-droid-org
sonar.projectKey=azconcept-droid-org
sonar.sources=src
sonar.tests=test
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.9,3.10,3.11

# Exclude patterns
sonar.exclusions=**/test/**,**/node_modules/**,**/*.test.js
